version: '3.7'
services:
  chatgpt-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chatgpt-api-single
    ports:
      - "4000:4000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
